#!/usr/bin/env python
import sys, os

# Add the badbadger root to the PYTHONPATH
sys.path.append(
  os.path.dirname( # BadBadger root
    os.path.dirname( # scripts/
      os.path.realpath(__file__)))) # this script

from badbadger import main
main.main()
